name: CI

on:
  pull_request:
    branches: [prd, dev, stg]

jobs:
  checkMeds:
    name: Check Meds (merge every day)
    runs-on: ubuntu-latest
    steps:
      - name: Check Meds
        uses: byuawsfhtl/MedsAction@v1.0.0

  checkStandard:
    name: Python Standard Check
    runs-on: ubuntu-latest
    steps:
      - name: Check Standard
        uses: byuawsfhtl/PythonStandardAction@v1.2.0

  checkTestCoverage:
    name: Test Coverage Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Check Test Coverage
        uses: ./
        with:
          minimum_coverage: '80'
          test_paths: 'tests/,test/,**/test_*.py,**/tests.py'
          source_paths: '.'
          exclude_paths: 'tests/,test/,**/test_*.py,**/tests.py,setup.py,conftest.py'
          fail_on_low_coverage: 'false'
          report_format: 'term'
